---
version: 2
jobs:
  build:
    working_directory: /Pink2
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: Install Build Depends
          command: |
                  echo APT::Install-Recommends "0"; >> /etc/apt/apt.conf &&
                  echo APT::Install-Suggests "0"; >> /etc/apt/apt.conf &&
                  apt-get update && apt-get install \
                  --no-install-recommends \
                  -y \
                  qt5-default qt5-qmake qtbase5-dev-tools \
                  qttools5-dev-tools build-essential libboost-dev \
                  libboost-system-dev \
                  libboost-filesystem-dev \
                  libboost-program-options-dev \
                  libboost-thread-dev libssl-dev \
                  libdb++-dev \
                  libminiupnpc-dev \
                  libqrencode-dev \
                  wget \
                  ca-certificates
      - run:
          name: Build bdb4.8
          command: |
                 cd src
                 BDB_PREFIX=/Pink2/src/db4
                 mkdir -p $BDB_PREFIX
                 wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
                 echo '12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef db-4.8.30.NC.tar.gz' | sha256sum -c
                 tar -xzvf db-4.8.30.NC.tar.gz
                 cd db-4.8.30.NC/build_unix/
                 ../dist/configure --enable-cxx \
                 --disable-shared --with-pic --prefix=$BDB_PREFIX
                 make install
      - run:
          name: Build openssl
          command: |
                 cd src
                 OPENSSL_PREFIX=/Pink2/src/openssl
                 mkdir -p $OPENSSL_PREFIX
                 wget 'https://www.openssl.org/source/openssl-1.0.2l.tar.gz'
                 echo 'ce07195b659e75f4e1db43552860070061f156a98bb37b672b101ba6e3ddf30c openssl-1.0.2l.tar.gz' | sha256sum -c
                 tar -xzvf openssl-1.0.2l.tar.gz
                 cd openssl-1.0.2l
                 ./Configure  linux-x86_64 no-ssl2 no-ssl3 no-comp --prefix=$OPENSSL_PREFIX no-shared
                 make depend
                 make install
      - run:
          name: Build pinkcoin-qt
          command: |
                  qmake \
                  USE_UPNP=1 \
                  USE_DBUS=1 \
                  CONFIG+=c++11 \
                  USE_QRCODE=1 \
                  STATIC=all \
                  RELEASE=1 \
                  BDB_LIB_PATH=/Pink2/src/db4/lib \
                  BDB_INCLUDE_PATH=/Pink2/src/db4/include \
                  OPENSSL_INCLUDE_PATH=/Pink2/src/openssl/include \
                  OPENSSL_LIB_PATH=/Pink2/src/openssl/lib
                  make
                  strip Pinkcoin-Qt
      - store_artifacts:
          path: Pinkcoin-Qt
          destination: pinkcoin-qt
      - run:
          name: Build headless bin pink2d
          command: |
                  cd src
                  make -f makefile.unix RELEASE=1 STATIC=all USE_UPNP=1 USE_QRCODE=1 BDB_INCLUDE_PATH=/Pink2/src/db4/include BDB_LIB_PATH=/Pink2/src/db4/lib OPENSSL_LIB_PATH=/Pink2/src/openssl/lib OPENSSL_INCLUDE_PATH=/Pink2/src/openssl/include
                  strip pink2d
      - store_artifacts:
          path: src/pink2d
          destination: pink2d
