---
version: 2
jobs:
  build:
    working_directory: /Pink2
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: Install Build Depends
          command: |
                  echo APT::Install-Recommends "0"; >> /etc/apt/apt.conf &&
                  echo APT::Install-Suggests "0"; >> /etc/apt/apt.conf &&
                  apt-get update && apt-get install \
                  --no-install-recommends \
                  -y \
                  qt5-default qt5-qmake qtbase5-dev-tools \
                  qttools5-dev-tools build-essential libboost-dev \
                  libboost-system-dev \
                  libboost-filesystem-dev \
                  libboost-program-options-dev \
                  libboost-thread-dev libssl-dev \
                  libdb++-dev \
                  libminiupnpc-dev \
                  libqrencode-dev \
                  wget \
                  ca-certificates
      - run:
          name: Build bdb4.8
          command: |
                 cd src
                 BDB_PREFIX=/Pink2/src/db4
                 mkdir -p $BDB_PREFIX
                 wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
                 echo '12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef db-4.8.30.NC.tar.gz' | sha256sum -c
                 tar -xzvf db-4.8.30.NC.tar.gz
                 cd db-4.8.30.NC/build_unix/
                 ../dist/configure --enable-cxx \
                 --disable-shared --with-pic --prefix=$BDB_PREFIX
                 make install
      - run:
          name: Build pinkcoin-qt
          command: |
                  qmake USE_UPNP=1 \
                  USE_DBUS=1 \
                  CONFIG+=c++11 \
                  USE_QRCODE=1 \
                  BDB_LIB_PATH=/Pink2/src/db4/lib \
                  BDB_INCLUDE_PATH=/Pink2/src/db4/include
                  make
      - store_artifacts:
          path: Pinkcoin-Qt
          destination: pinkcoin-qt
      - run:
          name: Build headless bin pink2d
          command: |
                  cd src
                  export BDB_INCLUDE_PATH=/Pink2/src/db4/include
                  export BDB_LIB_PATH=/Pink2/src/db4/lib
                  make -f makefile.unix
      - store_artifacts:
          path: src/pink2d
          destination: pink2d
