---
version: 2
jobs:
  build:
    working_directory: ~/Pink2
    docker:
      - image: ubuntu:xenial
    steps:
      - checkout
      - run:
          name: Install Build Depends
          command: |
                  apt-get update && apt-get install --no-install-recommends \
                  -y qt5-default qt5-qmake qtbase5-dev-tools \
                  qttools5-dev-tools build-essential libboost-dev \
                  libboost-system-dev \
                  libboost-filesystem-dev \
                  libboost-program-options-dev \
                  libboost-thread-dev libssl-dev \
                  libdb++-dev \
                  libminiupnpc-dev \
                  libqrencode-dev \
                  wget
      - run:
          name: Build bdb4.8
          command: |
                 cd src
                 PINKCOIN_ROOT=$(pwd)
                 BDB_PREFIX="${BITCOIN_ROOT}/db4"
                 mkdir -p $BDB_PREFIX
                 wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
                 echo '12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef db-4.8.30.NC.tar.gz' | sha256sum -c
                 tar -xzvf db-4.8.30.NC.tar.gz
                 cd db-4.8.30.NC/build_unix/
                 ../dist/configure --enable-cxx \
                 --disable-shared --with-pic --prefix=$BDB_PREFIX
                 make install
      - run:
          name: Build pinkcoin
          command: |
                  qmake USE_UPNP=1 USE_DBUS=1 USE_QRCODE=1 \
                  BDB_LIB_PATH=~/Pink2/src/db4/lib \
                  BDB_INCLUDE_PATH=~/Pink2/src/db4/include
                  make
      - store_artifacts:
          path: Pinkcoin-Qt
          destination: binary
